# Generated by Django 3.0.5 on 2020-04-20 23:35
import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Character",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("full_name", models.CharField(max_length=200)),
                ("total_cp", models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Skill",
            fields=[
                (
                    "id",
                    models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID"),
                ),  # noqa E501
                ("cost", models.IntegerField(default=2)),
                ("description", models.TextField(null=True)),
                (
                    "prerequisite",
                    models.ForeignKey(
                        null=True, on_delete=django.db.models.deletion.SET_NULL, to="characters.Skill"
                    ),  # noqa E501
                ),
            ],
        ),
        migrations.CreateModel(
            name="Subskill",
            fields=[
                (
                    "id",
                    models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID"),
                ),  # noqa E501
                (
                    "parent_skill",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="characters.Skill"),  # noqa E501
                ),
            ],
        ),
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID"),
                ),  # noqa E501
                (
                    "characters",
                    models.ForeignKey(
                        null=True, on_delete=django.db.models.deletion.SET_NULL, to="characters.Character"  # noqa E501
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="character", name="skills", field=models.ManyToManyField(to="characters.Skill")
        ),
    ]
