# Generated by Django 3.0.5 on 2020-04-21 17:05
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [("characters", "0001_initial")]

    operations = [
        migrations.RemoveField(model_name="character", name="skills"),
        migrations.RemoveField(model_name="skill", name="cost"),
        migrations.AddField(
            model_name="character",
            name="subskills",
            field=models.ManyToManyField(blank=True, null=True, to="characters.Subskill"),
        ),
        migrations.AddField(model_name="subskill", name="cost", field=models.IntegerField(default=2, null=True)),
    ]
