# Generated by Django 3.0.5 on 2020-04-21 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0002_auto_20200421_1705'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='name',
            field=models.TextField(default='Harhar'),
            preserve_default=False,
        ),
    ]
