# Generated by Django 3.0.5 on 2020-04-21 19:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0005_auto_20200421_1754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='full_name',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='skill',
            name='prerequisite',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='characters.Skill'),
        ),
    ]
