# Generated by Django 3.0.5 on 2020-04-25 17:47
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [("characters", "0006_auto_20200421_1914")]

    operations = [
        migrations.RemoveField(model_name="event", name="characters"),
        migrations.AddField(
            model_name="event",
            name="characters",
            field=models.ManyToManyField(blank=True, null=True, to="characters.Character"),
        ),
    ]
