# Generated by Django 3.0.5 on 2020-04-25 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0008_auto_20200425_1804'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='characters',
        ),
    ]
