# Generated by Django 3.0.5 on 2020-04-25 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0010_character_events'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='characters',
            field=models.ManyToManyField(blank=True, to='characters.Character'),
        ),
    ]
