# Generated by Django 3.0.5 on 2020-04-25 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0011_event_characters'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateField(),
        ),
    ]
