# Generated by Django 3.0.5 on 2020-04-25 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0013_remove_character_events'),
    ]

    operations = [
        migrations.RenameField(
            model_name='character',
            old_name='total_cp',
            new_name='starting_cp',
        ),
    ]
