# Generated by Django 3.0.5 on 2020-04-26 04:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0017_auto_20200426_0432'),
    ]

    operations = [
        migrations.RenameField(
            model_name='skill',
            old_name='prerequisite',
            new_name='parent',
        ),
    ]
