# Generated by Django 3.0.5 on 2020-04-26 04:51

from django.db import migrations
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0018_auto_20200426_0436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='characters.Skill'),
        ),
    ]
